### PR TITLE
Feature: Scoreboard component 🎁

### PR DESCRIPTION
**Pull request by MosesSupposes**
The app will now --statically -- display the names and scores of the players in a game.
Give me feedback about the API, stylistic mismatches, overall usefulness, or any of the like; I can edit and resubmit a PR!

preview of the new feature

### CODE REVIEW

**Comment by MosesSupposes** [comment]
Also, if you like I can link it up to state and get it functional. (Really I just want a valid excuse to try out that sick useState API you introduced me to recently. 😉)

**Comment by secantsquared** [comment]
@MosesSupposes Technically this is just a demo application, but by all means go to town for sure!... 
I will be turning my attention to from time to time as an experimental piece - in fact its actually the first project from the React documentation that is introduced and I am really just using it for various experimental work and to mess around with various change log aspects of React as it evolves.  I have a Redux mimic going with the useState/Context/Reducer API but haven't pushed it up but go for it and we can compare the diffs down the road, by all means... also let me know if you want anything for the other project I enjoyed that one.  I started another round of PMing but it is part time.

**Comment by secantsquared** [comment]
@MosesSupposes However, if you really want to work on something worthwhile that isn't a demo app and one I'm really curious in putting into production... message me on Slack, I have an idea for something I want to run by you and see what you thought and if it was something to pursue.

**Comment by secantsquared** [comment]
Feature #1  Accepted 
Feature merged to master. 
TY @MosesSupposes for your contribution.

**Pull request merged**
